name: ${PROJECT_NAME}

networks:
  piedrazul_net:
    name: piedrazul_net

include:
  - ./db.yml
  - ./keycloak.yml
  - ./backend.yml
  - ./traefik.yml

services:
  keycloak:
    command: [ "start", "--import-realm" ]
    environment:
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: "true"
      KC_PROXY_HEADERS: xforwarded
    ports:
      - "127.0.0.1:${KC_PORT}:${KC_PORT}"
    expose:
      - "${KC_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KC_HOSTNAME}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=${KC_PORT}"

  backend:
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${API_PUBLIC_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
