---
- name: Actualizar índice de paquetes apt
  ansible.builtin.apt:
    cache_valid_time: 3600

- name: Instalar paquetes base
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
      - ca-certificates
      - lsb-release
    state: present

- name: Configurar timezone
  community.general.timezone:
    name: America/Bogota
