---
- name: Restart app stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    project_name: "{{ compose_project_name }}"
    files:
      - prod.yml
    state: present
    env_files:
      - .env
      - image.env
