package co.edu.unicauca.piedrazul.backend.shared.enums;

public enum AuditAction {

    USUARIO_CREADO, USUARIO_MODIFICADO, USUARIO_DESACTIVADO,
    CITA_AGENDADA, CITA_REAGENDADA,
    HISTORIA_CLINICA_CREADA, HISTORIA_CLINICA_CONSULTADA,
    LOGIN_EXITOSO, LOGIN_FALLIDO
    /*
    // usuarios
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    // citas
    APPOINTMENT_CREATED,
    APPOINTMENT_RESCHEDULED,

    // historia clínica
    CLINICAL_RECORD_CREATED
     */
}
