package co.edu.unicauca.piedrazul.backend.shared.enums;

public enum AuditAction {
    CITA_AGENDADA,
    USUARIO_CREADO,
    USUARIO_ACTIVADO,
    USUARIO_DESACTIVADO,
    PACIENTE_MODIFICADO,
    HISTORIA_CLINICA_CREADA,
    HISTORIA_CLINICA_CONSULTADA,
    LOGIN_EXITOSO,
    LOGIN_FALLIDO
}
