package co.edu.unicauca.piedrazul.backend.shared.enums;

public enum AuditAction {
    CITA_AGENDADA,
    USUARIO_CREADO,
    USUARIO_ACTIVADO,
    USUARIO_DESACTIVADO,
    ROL_ASIGNADO,
    ROL_REVOCADO,
    PACIENTE_MODIFICADO,
    CONTROL_MEDICO_CREADO,
    CONTROL_MEDICO_CONSULTADO,
    CONTROL_MEDICO_MODIFICADO,
    DESCANSO_CREADO,
    DESCANSO_ELIMINADO,
    DESCANSO_RECORTADO,
    LOGIN_EXITOSO,
    LOGIN_FALLIDO
}
